obj-$(CONFIG_MU509)    += mu509.o
obj-$(CONFIG_MW100)    += mw100.o
obj-$(CONFIG_MT6229)   += mt6229.o
obj-$(CONFIG_MT6229_UNAP)   += mt6229_unap.o
obj-$(CONFIG_SEW868)   += sew868.o
obj-$(CONFIG_MI700)   += mi700.o
obj-$(CONFIG_SC6610)   += sc6610.o
obj-$(CONFIG_ME906E)    += me906e.o