#Makefile for out of kernel builds 
# used for building driver module against existing kernel
# kpowell@kionix.com

#
# Makefile for industrial I/O Magnetometer sensors
#
obj-$(CONFIG_KIONIX_KMX61G_SENSOR) := kmx61.o