
#if defined(CONFIG_BATTERY_BTUCNRD005)
/* bt-d004-3800mah 3800 mAh - Generated by BCM Ver 1.0.5 */

battery_graph_prop rt5025_battery_param1[] =
{
	{ 4169, 1000 },
	{ 4122,  980 },
	{ 4048,  900 },
	{ 3971,  800 },
	{ 3903,  700 },
	{ 3842,  600 },
	{ 3795,  500 },
	{ 3762,  400 },
	{ 3731,  250 },
	{ 3707,  150 },
	{ 3672,   70 },
	{ 3667,   50 },
	{ 3651,   20 },
	{ 3500,    0 },
};
battery_graph_prop rt5025_battery_param2[] =
{
	{  450,   50 },
	{  250,    0 },
	{   50, -150 },
	{   50,   10 },
	{ 3500, 3893 },
};
#endif
